//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.umk.tiebashenqi.activity.register;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ViewFlipper;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.umk.andx3.view.ScrollingTextView;
import com.umk.tiebashenqi.R.id;
import com.umk.tiebashenqi.R.layout;

public final class RegisterActivity_
    extends RegisterActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_register);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
    }

    private void afterSetContentView_() {
        mBtnNext = ((Button) findViewById(id.reg_btn_next));
        mBtnPrevious = ((Button) findViewById(id.reg_btn_previous));
        header_layout_rightview_container = ((LinearLayout) findViewById(id.header_layout_rightview_container));
        mVfFlipper = ((ViewFlipper) findViewById(id.reg_vf_viewflipper));
        header_stv_title = ((ScrollingTextView) findViewById(id.header_stv_title));
        header_stv_subtitle = ((ScrollingTextView) findViewById(id.header_stv_subtitle));
        {
            View view = findViewById(id.reg_btn_previous);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RegisterActivity_.this.reg_btn_previous();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.reg_btn_next);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RegisterActivity_.this.reg_btn_next();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static RegisterActivity_.IntentBuilder_ intent(Context context) {
        return new RegisterActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, RegisterActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public RegisterActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
