//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.umk.tiebashenqi.activity.tieba;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.ExpandableListView;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.umk.andx3.R.id;
import com.umk.andx3.R.layout;
import com.umk.andx3.view.ScrollingTextView;

public final class TiebaTieziActivity_
    extends TiebaTieziActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_tieba_tiezi);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
    }

    private void afterSetContentView_() {
        header_layout_right_imagebuttonlayout = ((LinearLayout) findViewById(id.header_layout_right_imagebuttonlayout));
        header_stv_title = ((ScrollingTextView) findViewById(id.header_stv_title));
        header_tv_subtitle = ((TextView) findViewById(id.header_tv_subtitle));
        tiezi_elv = ((ExpandableListView) findViewById(id.tiezi_elv));
        header_ib_right_imagebutton = ((ImageButton) findViewById(id.header_ib_right_imagebutton));
        {
            View view = findViewById(id.header_layout_left_imagebuttonlayout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TiebaTieziActivity_.this.header_layout_left_imagebuttonlayout();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.header_layout_right_imagebuttonlayout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TiebaTieziActivity_.this.header_layout_right_imagebuttonlayout();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static TiebaTieziActivity_.IntentBuilder_ intent(Context context) {
        return new TiebaTieziActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, TiebaTieziActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public TiebaTieziActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
